### PR TITLE
add line shape

### PR DESCRIPTION
**Pull request by Architrixs**
What this PR adds:
- Line shape

Have checked that it works with Annotorious.

Let me know for any changes, I will be opening a PR for related change in Annotorious.

### CODE REVIEW

**Comment by Architrixs** [comment]
TODO:
- [x] Related changes in OpenseaDragon if any
- [x] Add button for Line in Toolbar plugin
- [x] check other plugins are working for this, Mainly ShapeLabels

**Comment by Architrixs** [comment]
Hey, @rsimon I was hoping you could merge this... LGTM?

**Comment by rsimon** [comment]
Just tested it - nice! Merged the PR. Many thanks! 🙏

**Comment by Architrixs** [comment]
this one too... https://github.com/recogito/annotorious-openseadragon/pull/131,

Thanks, And Do you think you'll  make a new release on npm for this soon ...?

**Comment by rsimon** [comment]
Yes, I'm aiming for a new release this week.

**Pull request merged**
